In [1]:
#NumPy

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np 

In [5]:
#Creating Arrays

In [6]:
sample_array = np.array([1,2,3,4])

In [7]:
sample_array

array([1, 2, 3, 4])

In [8]:
# 2D Array(a Matrix) with 2 rows and 2 coloumns 

In [9]:
sample_array_2 = np.array([[1,2],[3,4]])

In [10]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [11]:
#3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [14]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
#Dimensions

In [17]:
#0-D Array(scalar) 5
#1-D Array(Vector) [1,2,3,4]
#2-D Array(Matrix) ([rows, columns])
#3-D Array(Tensors)(page, row, column)

In [18]:
#Array Properties

In [19]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [20]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#shape

In [22]:
sample_array.shape

(2, 3)

In [23]:
#dimensions

In [24]:
sample_array.ndim

2

In [25]:
# total elements

In [26]:
sample_array.size

6

In [27]:
sample_array.dtype

dtype('int64')

In [28]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [30]:
sample_tensor_3.shape

(2, 2, 2)

In [31]:
sample_tensor_3.ndim

3

In [32]:
sample_tensor_3.size

8

In [33]:
sample_tensor_3.dtype

dtype('int64')

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
# Indexing & slicing 

In [40]:
sample_array = np.array([10,20,30,40])

In [41]:
sample_array

array([10, 20, 30, 40])

In [42]:
sample_array[0]

np.int64(10)

In [43]:
sample_array[1]

np.int64(20)

In [44]:
sample_array[-1]

np.int64(40)

In [45]:
#Slicing

In [46]:
sample_array[1:3]

array([20, 30])

In [47]:
# Array operations 

In [48]:
a = np.array([1,2,3])

In [49]:
b = np.array([4,5,6])

In [50]:
a

array([1, 2, 3])

In [51]:
b

array([4, 5, 6])

In [52]:
a + b

array([5, 7, 9])

In [53]:
a -  b

array([-3, -3, -3])

In [54]:
a * b

array([ 4, 10, 18])

In [55]:
a / b

array([0.25, 0.4 , 0.5 ])

In [56]:
sample_array = np.array([1,4,9])

In [57]:
sample_array

array([1, 4, 9])

In [58]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [59]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [60]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [61]:
# statistical functions

In [62]:
sample_array = np.array([1,2,3,4,5])

In [63]:
sample_array

array([1, 2, 3, 4, 5])

In [65]:
np.mean(sample_array)

np.float64(3.0)

In [66]:
np.median(sample_array)

np.float64(3.0)

In [67]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [68]:
np.min(sample_array)

np.int64(1)

In [69]:
np.max(sample_array)

np.int64(5)

In [70]:
# Reshaping Arrays

In [72]:
sample_array = np.arange(6)

In [73]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [75]:
reshaped = sample_array.reshape(2,3)

In [76]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
# Flattening

In [78]:
sample_array = np.array([[1,2],[3,4]])

In [79]:
sample_array

array([[1, 2],
       [3, 4]])

In [80]:
sample_array.flatten()

array([1, 2, 3, 4])

In [81]:
# Joining Arrays

In [82]:
a = np.array([1,2])

In [83]:
b = np.array([3,4])

In [84]:
a

array([1, 2])

In [85]:
b

array([3, 4])

In [86]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [87]:
# splitting Arrays

In [88]:
sample_array = np.array([1,2,3,4])

In [89]:
sample_array

array([1, 2, 3, 4])

In [90]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [91]:
# Random Module

In [92]:
np.random.rand(3)

array([0.22669504, 0.95531774, 0.71570903])

In [93]:
np.random.randint(1,10,5)

array([4, 1, 2, 9, 2], dtype=int32)

In [95]:
sample_array = np.array([[1,2],[3,4]])

In [96]:
sample_array

array([[1, 2],
       [3, 4]])

In [97]:
np.sum(sample_array, axis=0)

array([4, 6])

In [98]:
np.sum(sample_array,axis=1)

array([3, 7])

In [99]:
# NaN & Missing Values

In [100]:
sample_array = np.array([1,np.nan,3])

In [101]:
sample_array

array([ 1., nan,  3.])

In [102]:
# create two numpy arrays and perform element wise addition,substraction,multiplication and modulous operations 

In [103]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a % b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 2 3]
